In [1]:
root = "C:/Users/v-wangwilli/projects/nepas"
setwd(root)
.libPaths(file.path(root, "renv/library/windows/R-4.4/x86_64-w64-mingw32"))

library(jsonlite)
library(tidyverse)

source("script/processors.R")

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.6
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.1     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.2.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter()  masks stats::filter()
✖ purrr::flatten() masks jsonlite::flatten()
✖ dplyr::lag()     masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [2]:
years = 1967:1979

bps_raw = map(
  years,
  \(year) process_year(year, root = "data/raw_ocr/")
) |> bind_rows()

# Output raw OCR data for manual validation
# bps_raw |>
#   select(
#     year, page_numbers, line_number, smsa_name:public_valuation
#   ) |>
#   write_csv("data/raw_ocr/bps_raw.csv")

bps = bps_raw |> 
  mutate(
    total_units_diff = total_units - rowSums(pick(private_total, public_units)),
    private_total_diff = private_total - rowSums(pick(private_1_unit:private_5plus_units)),
    total_valuation_diff = total_valuation - rowSums(pick(private_valuation, public_valuation)),
    private_valuation_diff = private_valuation - rowSums(pick(private_1_unit_val:private_5plus_units_val))
  )

Out of all the 46000 validation checks (4 per row), how many pass?

In [26]:
validations = bps |>
  pivot_longer(contains("diff"), names_to = "diff_type", values_to = "diff_value") |>
  mutate(
    abs_diff_value = abs(diff_value),
    all_units_na = if_all(total_units:private_structures, \(x) is.na(x)),
    all_vals_na = if_all(total_valuation:public_valuation, \(x) is.na(x)),
    all_private_units_na = if_all(total_units:private_5plus_units, \(x) is.na(x)), # Particular mode where all entries are (S) except public units
    across(all_units_na:all_private_units_na, \(col) as.numeric(col)),
    all_na = pmin(all_units_na & all_vals_na)
  )

validations |>
  count(abs_diff_value) |>
  mutate(prop = round(n / sum(n), 4))

   abs_diff_value n     prop
1      0          42038 0.9139
2      1           3320 0.0722
3      2             51 0.0011
4      3              8 0.0002
5      4              7 0.0002
6      5              2 0.0000
7      6              1 0.0000
8      7              1 0.0000
9      8              1 0.0000
10     9              1 0.0000
11    10              5 0.0001
12    11              1 0.0000
13    14              1 0.0000
14    15              3 0.0001
15    16              1 0.0000
16    19              1 0.0000
17    20              3 0.0001
18    23              1 0.0000
19    24              2 0.0000
20    25              1 0.0000
21    27              1 0.0000
22    30              3 0.0001
23    31              1 0.0000
24    35              2 0.0000
25    36              2 0.0000
26    40              2 0.0000
27    50              1 0.0000
28    60              1 0.0000
29    61              1 0.0000
30    93              1 0.0000
31   100              2 0.0000
32   168              1 0.0000
33   169              1 0.0000
34   190              2 0.0000
35   200              1 0.0000
36   206              1 0.0000
37   242              1 0.0000
38   345              2 0.0000
39   374              1 0.0000
40   375              1 0.0000
41   402              1 0.0000
42   440              1 0.0000
43   491              2 0.0000
44   492              1 0.0000
45   493              1 0.0000
46   696              1 0.0000
47   899              1 0.0000
48   900              1 0.0000
49  1000              1 0.0000
50  1434              2 0.0000
51  1578              1 0.0000
52  2002              1 0.0000
53  2309              1 0.0000
54 10000              1 0.0000
55    NA            507 0.0110

In [27]:
# Distribution of types of validation fails for small differences
validations |>
  filter(abs_diff_value %in% 1:5) |>
  count(abs_diff_value, diff_type)

   abs_diff_value diff_type              n
1  1              private_valuation_diff 3099
2  1              total_valuation_diff    221
3  2              private_total_diff        6
4  2              private_valuation_diff   44
5  2              total_valuation_diff      1
6  3              private_total_diff        6
7  3              private_valuation_diff    2
8  4              private_total_diff        6
9  4              private_valuation_diff    1
10 5              private_valuation_diff    1
11 5              total_valuation_diff      1

In [29]:
# If validation failed because sum is NA, are all entries in that row NA? (that would be good)
validations |>
  filter(is.na(diff_value)) |>
  count(!str_detect(diff_type, "valuation") & (all_units_na | all_private_units_na & public_units == 0) | str_detect(diff_type, "valuation") & all_vals_na) |>
  mutate(prop = round(n / 46000, 3))

  |...  n   prop
1 FALSE  59 0.001
2  TRUE 448 0.010

In [32]:
validations |>
  filter(is.na(diff_value) & all_units_na == 0 & (all_private_units_na == 0 | public_units != 0) & !str_detect(diff_type, "valuation")) |>
  distinct(year, page_numbers, line_number, smsa_name)

  year page_numbers     line_number smsa_name
1 1967 pages_13_14.json 2           LAREDO
2 1969 pages_17_18.json 44          ODESSA

In [33]:
validations |>
  filter(
    abs_diff_value > 2 |
    is.na(abs_diff_value) & str_detect(diff_type, "valuation") & all_vals_na == 0 | 
    is.na(abs_diff_value) & !str_detect(diff_type, "valuation") & all_units_na == 0 & (all_private_units_na == 0 | public_units != 0)
  ) |>
  distinct(line_number, page_numbers, year) |>
  nrow() |>
  {\(x) round(x / 11500, 3)}()

[1] 0.009

92.4% of validation checks match exactly, including 1.0% of checks where all entries are NA. 7.2% have the expected and actual totals differ by 1, and all of them are valuation checks, which are expected to differ due to rounding. Thus, at least 99.6% of validation checks pass. 0.9% of rows have at least one validation check fail.

Note: some rows may have errors that compensate for each other -- an increase in one column is canceled out by a decrease in another. I consider this possibility relatively unlikely.

In [ ]:
validations |>
  filter(abs_diff_value > 1 & !str_detect(diff_type, "valuation"))

At line 45, 15-16, 1967 and line 47, 15-16, 1967, there are errors in addition in the original tables. I corrected all failed validation checks for units outcomes. Most of these were "transpositions" between consecutive rows, where a null in one row was switched with a number in the other.

In [34]:
bps_corrected = map(
  years,
    \(year) process_year(year, root = "data/cleaned_ocr/")
) |> bind_rows()

bps_corrected = bps_corrected |> 
  mutate(
    total_units_diff = total_units - rowSums(pick(private_total, public_units)),
    private_total_diff = private_total - rowSums(pick(private_1_unit:private_5plus_units)),
    total_valuation_diff = total_valuation - rowSums(pick(private_valuation, public_valuation)),
    private_valuation_diff = private_valuation - rowSums(pick(private_1_unit_val:private_5plus_units_val))
  )

validations_corrected = bps_corrected |>
  pivot_longer(contains("diff"), names_to = "diff_type", values_to = "diff_value") |>
  mutate(
    abs_diff_value = abs(diff_value),
    all_na = if_all(total_units:public_valuation, \(x) is.na(x)) |> as.numeric()
  )

validations_corrected |>
  count(abs_diff_value) |>
  mutate(prop = round(n / sum(n), 4))

validations_corrected |>
  filter(abs_diff_value > 1 & !str_detect(diff_type, "valuation")) |>
  nrow() |>
  {\(x) x == 2}()

   abs_diff_value n     prop
1      0          42076 0.9147
2      1           3321 0.0722
3      2             45 0.0010
4      3              2 0.0000
5      4              1 0.0000
6      5              2 0.0000
7      9              1 0.0000
8     10              2 0.0000
9     11              1 0.0000
10    14              1 0.0000
11    15              1 0.0000
12    19              1 0.0000
13    25              1 0.0000
14    27              1 0.0000
15    30              3 0.0001
16    31              1 0.0000
17    36              2 0.0000
18    40              2 0.0000
19    50              1 0.0000
20    60              1 0.0000
21    61              1 0.0000
22    93              1 0.0000
23   100              2 0.0000
24   168              1 0.0000
25   169              1 0.0000
26   190              2 0.0000
27   200              1 0.0000
28   206              1 0.0000
29   242              1 0.0000
30   345              2 0.0000
31   374              1 0.0000
32   375              1 0.0000
33   402              1 0.0000
34   440              1 0.0000
35   491              2 0.0000
36   492              1 0.0000
37   493              1 0.0000
38   696              1 0.0000
39   899              1 0.0000
40   900              1 0.0000
41  1000              1 0.0000
42  1434              2 0.0000
43  1578              1 0.0000
44  2002              1 0.0000
45  2309              1 0.0000
46 10000              1 0.0000
47    NA            503 0.0109

[1] TRUE

The fixed data has 2 invalid sums, as we expect.

In [279]:
validations |>
  filter(abs_diff_value >= 100 & str_detect(diff_type, "valuation"))

   line_number page_numbers     year smsa_group smsa_name
1  50          pages_15_16.json 1967 130        OUTSIDE CENTRAL CITY
2  49          pages_23_24.json 1967 195        SPRINGFIELD, OHIO
3  52          pages_25_26.json 1969 213        TYLER, TEX.
4  2           pages_07_08.json 1972  55        DALLAS
5  59          pages_13_14.json 1972 125        LIMA
6  60          pages_13_14.json 1972 125        OUTSIDE CENTRAL CITY
7  13          pages_17_18.json 1972 149        MONROE.
8  14          pages_17_18.json 1972 149        OUTSIDE CENTRAL CITY
9  39          pages_01_02.json 1974  10        ANAHEIM.
10 55          pages_25_26.json 1974 231        CHICOPEE
11 43          pages_13_14.json 1975 120        LAFAYETTE, LA.
12 44          pages_13_14.json 1975 120        LAFAYETTE.
13 28          pages_17_18.json 1975 151        MIAMI, FLA.
14 29          pages_17_18.json 1975 151        MIAMI
15 33          pages_15_16.json 1976 134        OUTSIDE CENTRAL CITIES
16 60          pages_11_12.json 1977 106        ASHLAND.
17 61          pages_11_12.json 1977 106        HUNTINGTON
18 22          pages_01_02.json 1978   6        ALEXANDRIA, LA.
19 23          pages_01_02.json 1978   6        ALEXANDRIA
20 10          pages_15_16.json 1978 127        LANCASTER.
21 29          pages_23_24.json 1978 202        INSIDE CENTRAL CITIES.
22 53          pages_23_24.json 1978 209        RICHLAND-KENNEWICK-PASCO, WASH.
23 34          pages_05_06.json 1979  46        INSIDE CENTRAL CITIES.
24 34          pages_07_08.json 1979  63        ROCK ISLAND.
25 26          pages_09_10.json 1979  81        INSIDE CENTRAL CITIES
26 28          pages_09_10.json 1979  81        MOORHEAD
27 58          pages_17_18.json 1979 161        MIAMI, FLA.
   total_units private_total private_1_unit private_2_units private_3_4_units ⋯
1    320         320          320              0              0               ⋯
2   1623        1473         1033             10             12               ⋯
3    373         373          214             16              0               ⋯
4  10717       10533         2916            124              0               ⋯
5    242         242           43              0             15               ⋯
6    274         274          249             10              0               ⋯
7    878         878          447              0             24               ⋯
8    233         233           46             14              0               ⋯
9   1325        1325          872             52             50               ⋯
10   213         213           61              6              4               ⋯
11   340         340          340              0              0               ⋯
12   329         329          329              0              0               ⋯
13  6465        5716         2820            496            177               ⋯
14  1529        1035           87            280              6               ⋯
15   645         645          607             16             22               ⋯
16    92          92           40              4              0               ⋯
17   382         382           54              0             20               ⋯
18   245         245          203             38              4               ⋯
19   186         186          144             38              4               ⋯
20   173         173           18              4              0               ⋯
21  2061        2061         1236             82            225               ⋯
22  3259        3259         2150            162            203               ⋯
23   642         642          188             26              0               ⋯
24   389         389           32              6             11               ⋯
25   879         879          222            144             16               ⋯
26   317         317          107             70              4               ⋯
27 19895       19895         9027           1432            750               ⋯
   public_valuation outside_indicator inside_indicator smsa_indicator
1      0            1                 0                0
2   1848            0                 0                1
3      0            0                 0                1
4   2588            0                 0                0
5      0            0                 0                0
6      0            1                 0                0
7      0            0                 0                0
8      0            1                 0                0
9      0            0                 0                0
10     0            0                 0                0
11     0            0                 0                1
12     0            0                 0                0
13 18619            0                 0                1
14 12896            0                 0                0
15     0            1                 0                0
16     0            0                 0                0
17     0            0                 0                0
18     0            0                 0                1
19     0            0                 0                0
20     0            0                 0                0
21     0            0                 1                0
22     0            0                 0                1
23     0            0                 1                0
24     0            0                 0                0
25     0            0                 1                0
26     0            0                 0                0
27     0            0                 0                1
   city_indicator smsa_name_clean                diff_type
1  0              OUTSIDE CENTRAL CITY           private_valuation_diff
2  0              SPRINGFIELD, OHIO              total_valuation_diff
3  0              TYLER, TEX                     private_valuation_diff
4  1              DALLAS                         private_valuation_diff
5  1              LIMA                           private_valuation_diff
6  0              OUTSIDE CENTRAL CITY           private_valuation_diff
7  1              MONROE                         private_valuation_diff
8  0              OUTSIDE CENTRAL CITY           private_valuation_diff
9  1              ANAHEIM                        private_valuation_diff
10 1              CHICOPEE                       private_valuation_diff
11 0              LAFAYETTE, LA                  private_valuation_diff
12 1              LAFAYETTE                      private_valuation_diff
13 0              MIAMI, FLA                     private_valuation_diff
14 1              MIAMI                          private_valuation_diff
15 0              OUTSIDE CENTRAL CITIES         private_valuation_diff
16 1              ASHLAND                        private_valuation_diff
17 1              HUNTINGTON                     private_valuation_diff
18 0              ALEXANDRIA, LA                 private_valuation_diff
19 1              ALEXANDRIA                     private_valuation_diff
20 1              LANCASTER                      private_valuation_diff
21 0              INSIDE CENTRAL CITIES          private_valuation_diff
22 0              RICHLAND-KENNEWICK-PASCO, WASH private_valuation_diff
23 0              INSIDE CENTRAL CITIES          private_valuation_diff
24 1              ROCK ISLAND                    private_valuation_diff
25 0              INSIDE CENTRAL CITIES          private_valuation_diff
26 1              MOORHEAD                       private_valuation_diff
27 0              MIAMI, FLA                     private_valuation_diff
   diff_value abs_diff_value all_na
1    200        200          0
2  -2002       2002          0
3   -440        440          0
4   -206        206          0
5   -190        190          0
6    190        190          0
7   -168        168          0
8    169        169          0
9   1578       1578          0
10  1000       1000          0
11   491        491          0
12   491        491          0
13   899        899          0
14   900        900          0
15   242        242          0
16   345        345          0
17  -345        345          0
18   493        493          0
19   492        492          0
20  2309       2309          0
21   374        374          0
22 10000      10000          0
23   375        375          0
24   696        696          0
25  1434       1434          0
26  1434       1434          0
27  -402        402          0