In [ ]:
root = "C:/Users/v-wangwilli/projects/nepas"
setwd(root)
.libPaths(file.path(root, "renv/library/windows/R-4.4/x86_64-w64-mingw32"))

library(jsonlite)
library(tidyverse)

source("script/processors.R")

In [ ]:
years = 1967:1979

bps_raw = map(
  years,
  \(year) process_year(year, root = "data/raw_ocr/")
) |> bind_rows()

# Output raw OCR data for manual validation
# bps_raw |>
#   select(
#     year, page_numbers, line_number, smsa_name:public_valuation
#   ) |>
#   write_csv("data/raw_ocr/bps_raw.csv")

bps = bps_raw |> 
  mutate(
    total_units_diff = total_units - rowSums(pick(private_total, public_units)),
    private_total_diff = private_total - rowSums(pick(private_1_unit:private_5plus_units)),
    total_valuation_diff = total_valuation - rowSums(pick(private_valuation, public_valuation)),
    private_valuation_diff = private_valuation - rowSums(pick(private_1_unit_val:private_5plus_units_val))
  )

Out of all the 46000 validation checks (4 per row), how many pass?

In [201]:
validations = bps |>
  pivot_longer(contains("diff"), names_to = "diff_type", values_to = "diff_value") |>
  mutate(
    abs_diff_value = abs(diff_value),
    all_na = if_all(total_units:public_valuation, \(x) is.na(x)) |> as.numeric()
  )

validations |>
  count(abs_diff_value) |>
  mutate(prop = round(n / sum(n), 4))

   abs_diff_value n     prop
1      0          42038 0.9139
2      1           3320 0.0722
3      2             51 0.0011
4      3              8 0.0002
5      4              7 0.0002
6      5              2 0.0000
7      6              1 0.0000
8      7              1 0.0000
9      8              1 0.0000
10     9              1 0.0000
11    10              5 0.0001
12    11              1 0.0000
13    14              1 0.0000
14    15              3 0.0001
15    16              1 0.0000
16    19              1 0.0000
17    20              3 0.0001
18    23              1 0.0000
19    24              2 0.0000
20    25              1 0.0000
21    27              1 0.0000
22    30              3 0.0001
23    31              1 0.0000
24    35              2 0.0000
25    36              2 0.0000
26    40              2 0.0000
27    50              1 0.0000
28    60              1 0.0000
29    61              1 0.0000
30    93              1 0.0000
31   100              2 0.0000
32   168              1 0.0000
33   169              1 0.0000
34   190              2 0.0000
35   200              1 0.0000
36   206              1 0.0000
37   242              1 0.0000
38   345              2 0.0000
39   374              1 0.0000
40   375              1 0.0000
41   402              1 0.0000
42   440              1 0.0000
43   491              2 0.0000
44   492              1 0.0000
45   493              1 0.0000
46   696              1 0.0000
47   899              1 0.0000
48   900              1 0.0000
49  1000              1 0.0000
50  1434              2 0.0000
51  1578              1 0.0000
52  2002              1 0.0000
53  2309              1 0.0000
54 10000              1 0.0000
55    NA            507 0.0110

In [ ]:
# Distribution of types of validation fails for small differences
validations |>
  filter(abs_diff_value %in% 1:5) |>
  count(abs_diff_value, diff_type)

   abs_diff_value diff_type              n
1  1              private_valuation_diff 3099
2  1              total_valuation_diff    221
3  2              private_total_diff        6
4  2              private_valuation_diff   44
5  2              total_valuation_diff      1
6  3              private_total_diff        6
7  3              private_valuation_diff    2
8  4              private_total_diff        6
9  4              private_valuation_diff    1
10 5              private_valuation_diff    1
11 5              total_valuation_diff      1

In [ ]:
# If validation failed because sum is NA, are all entries in that row NA? (that would be good)
validations |>
  filter(is.na(diff_value)) |>
  count(all_na) |>
  mutate(prop = round(n / 46000, 3))

  all_na n   prop
1 0      119 0.003
2 1      388 0.008

In [275]:
validations |>
  filter(abs_diff_value > 2 | (is.na(abs_diff_value) & all_na == 0)) |>
  distinct(line_number, page_numbers, year) |>
  nrow() |>
  {\(x) round(x / 11500, 3)}()

[1] 0.009

92.2% of validation checks match exactly, including 0.8% of checks where all entries are NA. 7.2% have the expected and actual totals differ by 1, and all of them are valuation checks, which are expected to differ due to rounding. Thus, at least 99.4% of validation checks pass. 1.3% of rows have at least one validation check fail.

Note: some rows may have errors that compensate for each other -- an increase in one column is canceled out by a decrease in another. I consider this possibility relatively unlikely.

In [ ]:
validations |>
  filter(abs_diff_value > 1 & !str_detect(diff_type, "valuation"))

At line 45, 15-16, 1967 and line 47, 15-16, 1967, there are errors in addition in the original tables. I corrected all errors that had 2+ unit discrepancies for units outcomes. Most of these were "transpositions" between consecutive rows, where a null in one row was switched with a number in the other.

In [279]:
validations |>
  filter(abs_diff_value >= 100 & str_detect(diff_type, "valuation"))

   line_number page_numbers     year smsa_group smsa_name
1  50          pages_15_16.json 1967 130        OUTSIDE CENTRAL CITY
2  49          pages_23_24.json 1967 195        SPRINGFIELD, OHIO
3  52          pages_25_26.json 1969 213        TYLER, TEX.
4  2           pages_07_08.json 1972  55        DALLAS
5  59          pages_13_14.json 1972 125        LIMA
6  60          pages_13_14.json 1972 125        OUTSIDE CENTRAL CITY
7  13          pages_17_18.json 1972 149        MONROE.
8  14          pages_17_18.json 1972 149        OUTSIDE CENTRAL CITY
9  39          pages_01_02.json 1974  10        ANAHEIM.
10 55          pages_25_26.json 1974 231        CHICOPEE
11 43          pages_13_14.json 1975 120        LAFAYETTE, LA.
12 44          pages_13_14.json 1975 120        LAFAYETTE.
13 28          pages_17_18.json 1975 151        MIAMI, FLA.
14 29          pages_17_18.json 1975 151        MIAMI
15 33          pages_15_16.json 1976 134        OUTSIDE CENTRAL CITIES
16 60          pages_11_12.json 1977 106        ASHLAND.
17 61          pages_11_12.json 1977 106        HUNTINGTON
18 22          pages_01_02.json 1978   6        ALEXANDRIA, LA.
19 23          pages_01_02.json 1978   6        ALEXANDRIA
20 10          pages_15_16.json 1978 127        LANCASTER.
21 29          pages_23_24.json 1978 202        INSIDE CENTRAL CITIES.
22 53          pages_23_24.json 1978 209        RICHLAND-KENNEWICK-PASCO, WASH.
23 34          pages_05_06.json 1979  46        INSIDE CENTRAL CITIES.
24 34          pages_07_08.json 1979  63        ROCK ISLAND.
25 26          pages_09_10.json 1979  81        INSIDE CENTRAL CITIES
26 28          pages_09_10.json 1979  81        MOORHEAD
27 58          pages_17_18.json 1979 161        MIAMI, FLA.
   total_units private_total private_1_unit private_2_units private_3_4_units ⋯
1    320         320          320              0              0               ⋯
2   1623        1473         1033             10             12               ⋯
3    373         373          214             16              0               ⋯
4  10717       10533         2916            124              0               ⋯
5    242         242           43              0             15               ⋯
6    274         274          249             10              0               ⋯
7    878         878          447              0             24               ⋯
8    233         233           46             14              0               ⋯
9   1325        1325          872             52             50               ⋯
10   213         213           61              6              4               ⋯
11   340         340          340              0              0               ⋯
12   329         329          329              0              0               ⋯
13  6465        5716         2820            496            177               ⋯
14  1529        1035           87            280              6               ⋯
15   645         645          607             16             22               ⋯
16    92          92           40              4              0               ⋯
17   382         382           54              0             20               ⋯
18   245         245          203             38              4               ⋯
19   186         186          144             38              4               ⋯
20   173         173           18              4              0               ⋯
21  2061        2061         1236             82            225               ⋯
22  3259        3259         2150            162            203               ⋯
23   642         642          188             26              0               ⋯
24   389         389           32              6             11               ⋯
25   879         879          222            144             16               ⋯
26   317         317          107             70              4               ⋯
27 19895       19895         9027           1432            750               ⋯
   public_valuation outside_indicator inside_indicator smsa_indicator
1      0            1                 0                0
2   1848            0                 0                1
3      0            0                 0                1
4   2588            0                 0                0
5      0            0                 0                0
6      0            1                 0                0
7      0            0                 0                0
8      0            1                 0                0
9      0            0                 0                0
10     0            0                 0                0
11     0            0                 0                1
12     0            0                 0                0
13 18619            0                 0                1
14 12896            0                 0                0
15     0            1                 0                0
16     0            0                 0                0
17     0            0                 0                0
18     0            0                 0                1
19     0            0                 0                0
20     0            0                 0                0
21     0            0                 1                0
22     0            0                 0                1
23     0            0                 1                0
24     0            0                 0                0
25     0            0                 1                0
26     0            0                 0                0
27     0            0                 0                1
   city_indicator smsa_name_clean                diff_type
1  0              OUTSIDE CENTRAL CITY           private_valuation_diff
2  0              SPRINGFIELD, OHIO              total_valuation_diff
3  0              TYLER, TEX                     private_valuation_diff
4  1              DALLAS                         private_valuation_diff
5  1              LIMA                           private_valuation_diff
6  0              OUTSIDE CENTRAL CITY           private_valuation_diff
7  1              MONROE                         private_valuation_diff
8  0              OUTSIDE CENTRAL CITY           private_valuation_diff
9  1              ANAHEIM                        private_valuation_diff
10 1              CHICOPEE                       private_valuation_diff
11 0              LAFAYETTE, LA                  private_valuation_diff
12 1              LAFAYETTE                      private_valuation_diff
13 0              MIAMI, FLA                     private_valuation_diff
14 1              MIAMI                          private_valuation_diff
15 0              OUTSIDE CENTRAL CITIES         private_valuation_diff
16 1              ASHLAND                        private_valuation_diff
17 1              HUNTINGTON                     private_valuation_diff
18 0              ALEXANDRIA, LA                 private_valuation_diff
19 1              ALEXANDRIA                     private_valuation_diff
20 1              LANCASTER                      private_valuation_diff
21 0              INSIDE CENTRAL CITIES          private_valuation_diff
22 0              RICHLAND-KENNEWICK-PASCO, WASH private_valuation_diff
23 0              INSIDE CENTRAL CITIES          private_valuation_diff
24 1              ROCK ISLAND                    private_valuation_diff
25 0              INSIDE CENTRAL CITIES          private_valuation_diff
26 1              MOORHEAD                       private_valuation_diff
27 0              MIAMI, FLA                     private_valuation_diff
   diff_value abs_diff_value all_na
1    200        200          0
2  -2002       2002          0
3   -440        440          0
4   -206        206          0
5   -190        190          0
6    190        190          0
7   -168        168          0
8    169        169          0
9   1578       1578          0
10  1000       1000          0
11   491        491          0
12   491        491          0
13   899        899          0
14   900        900          0
15   242        242          0
16   345        345          0
17  -345        345          0
18   493        493          0
19   492        492          0
20  2309       2309          0
21   374        374          0
22 10000      10000          0
23   375        375          0
24   696        696          0
25  1434       1434          0
26  1434       1434          0
27  -402        402          0

# Preliminary validation

In [104]:
library(fixest)

feols(
  log(private_total) ~ treat | smsa_name_corrected + year, cluster = "smsa_name_corrected",
  data = bps_final |> filter(is.finite(adoption_year))
)

NOTE: 1/0 fixed-effect singleton was removed (1 observation).

OLS estimation, Dep. Var.: log(private_total)
Observations: 1,421
Fixed-effects: smsa_name_corrected: 125,  year: 13
Standard-errors: Clustered (smsa_name_corrected)
      Estimate Std. Error  t value Pr(>|t|)
treat  0.00127    0.06072 0.020917  0.98335
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 0.346217     Adj. R2: 0.919364
                 Within R2: 9.333e-7

In [107]:
renv::install("gregorsteiner/StaggeredSynthDiD")

# Downloading packages -------------------------------------------------------
- Downloading StaggeredSynthDiD from GitHub ... OK [4.8 Kb in 0.66s]
Successfully downloaded 1 package in 1.2 seconds.

The following package(s) will be installed:
- StaggeredSynthDiD [gregorsteiner/StaggeredSynthDiD@main]
These packages will be installed into "C:/Users/v-wangwilli/projects/nepas/renv/library/windows/R-4.4/x86_64-w64-mingw32".

# Installing packages --------------------------------------------------------
- Installing StaggeredSynthDiD ...              OK [built from source and cached in 5.8s]
Successfully installed 1 package in 6 seconds.

In [108]:
library(StaggeredSynthDiD)

Loading required package: data.table


Attaching package: 'data.table'


The following objects are masked from 'package:lubridate':

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


The following objects are masked from 'package:dplyr':

    between, first, last


The following object is masked from 'package:purrr':

    transpose

In [127]:
names(bps_final) |> length()

[1] 22

In [134]:
bps_final |>
  summarize(min(adoption_year))

  min(adoption_year)
1 1970

In [136]:
df = bind_rows(
  bps_final |>
    filter(is.infinite(adoption_year)),
  bps_final |>
    filter(adoption_year == 1970)
)

In [150]:
library(synthdid)

In [172]:
e = synthdid_estimate(
  Y = sdid_matrix,
  N0 = 30,
  T0 = 3
)

In [151]:
wide_df = df |>
  arrange(is.finite(adoption_year), year) |>
  mutate(log_private_total = log(private_total)) |>
  pivot_wider(id_cols = c(smsa_name_corrected, adoption_year), names_from = year, values_from = log_private_total)

In [121]:
as.data.frame(bps_final)$treat

   [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  [38] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  [75] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [112] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [149] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [186] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [223] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [260] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [297] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [334] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [371] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [408] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [445] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [482] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [519] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [556] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [593] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [630] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [667] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [704] 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 [741] 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0 1 0 0 0 0 0 0 1 0 0
 [778] 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0
 [815] 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
 [852] 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 [889] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1
 [926] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0
 [963] 0 0 0 0 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0 0
[1000] 1 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0
[1037] 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0
[1074] 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 1
[1111] 0 0 1 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0
[1148] 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0
[1185] 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1
[1222] 0 0 0 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 1 1 1 1 1 0 0 0 1 0 0 0 0 1
[1259] 0 1 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1
[1296] 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0
[1333] 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0
[1370] 0 1 0 1 0 1 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0
[1407] 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 0 1 0
[1444] 0 1 1 0 1 0 0 1 0 0 0 0 0 0 1 0 1 1 0 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0
[1481] 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 1 0 0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0
[1518] 0 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0
[1555] 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 0
[1592] 0 0 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
[1629] 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 1 1 0 0 0 1 0 1 1 1 0 0 0 1 1 0 0 0 1
[1666] 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 1
[1703] 0 0 0 0 1 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0 1 0 1 1 0 1 0 1 0 1 0 0 0 0 0 1 0
[1740] 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 1 1 0 0 1 1 1 1 1 0 0 1 0 1 0 0 0 1 0 0 0 1
[1777] 1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0
[1814] 0 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 1 1
[1851] 0 0 0 0 1 0 1 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0
[1888] 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 1 0 1
[1925] 1 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0
[1962] 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 1 0 0 1 1 0 1 0 0 1 0 0 0 1 0 1 0 1 1 0 1
[1999] 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 0 0 1 1 0 0 1 1 1 1 1
[2036] 1 0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 0 0 1 1 0 1 1 1 0
[2073] 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0
[2110] 1 0 1 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 0 1 0 1 0 0 0 1 1 0 0 0 1 1 0 0 0 0 0
[2147] 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 0 1 1 0 0 0 0 0
[2184] 0 0 0 1 1 0 0 0 1 0 1 0 1 1 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0
[2221] 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 1 0 1 0 0 0 0 0 1 0 0 1 1 0 1 0
[2258] 0 1 0 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1
[2295] 1 0 0 0 1 1 0 0 1 1 1 1 1 1 0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 0
[2332] 1 1 1 0 0 0 1 1 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 1 1
[2369] 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 0 1 0 1 0 0
[2406] 1 0 1 1 1 0 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1
[2443] 1 0 1 0 0 1 1 1 1 0 1 0 0 0 0 0 0 1 1 0 0 0 1 1 0 1 0 1 1 0 0 0 1 1 0 0 0
[2480] 1 0 0 0 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 1
[2517] 0 1 0 1 0 0 0 0 0 1 0 0 1 1 0 1 0 0 1 0 0 0 1 1 1 0 1 1 0 1 0 1 1 0 1 0 0
[2554] 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 1 1 1 0 0 1 1 0 0 1 1 1 1 1 1 0 1 0 1 0
[2591] 0 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 0 0 1 1 0 1 1 1 0 0 1 0 0 0 0
[2628] 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1
[2665] 1 0 0 0 0 1 1 0 0 0 0 1 0 1 0 1 0 0 1 0 1 1 1 0 0 1 1 0 0 0 0 0 1 0 0 1 0
[2702] 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 1 1 1 0 1 0 0 0 0 0 0 1 1
[2739] 0 0 0 1 1 0 1 0 1 1 0 0 1 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0
[2776] 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 1 0 1 0 1 0 0 0 0 0 1 0 0 1 1 0 1 0 0 1
[2813] 0 0 0 1 1 1 0 1 1 0 1 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 1 1
[2850] 1 0 0 1 1 1 0 0 1 1 1 1 1 1 0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 0
[2887] 1 1 1 0 0 0 1 1 0 1 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 1 1
[2924] 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 0 1 1 0 0 0 0 1 0 1 0 0 1 0
[2961] 0 1 0 1 1 1 0 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
[2998] 1 1 0 1 1 0 0 0 1 1 1 1 0 1 0 0 0 0 0 0 1 1 0 0 0 1 1 0 1 0 1 1 0 0 0 1 1
[3035] 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0
[3072] 0 0 0 1 1 1 0 1 0 1 0 0 0 0 0 1 0 0 1 1 0 1 0 0 1 0 0 0 1 1 1 0 1 1 0 1 0
[3109] 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 1 1 1 1 0 0 1 1 1 0 0 1 1 1 1
[3146] 1 1 0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 1 1 0 0 1 0 0 0 1 1 1 0 0 0 1 1 0 1 1 1
[3183] 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 1 1 1 1 0 0

In [35]:
bps_final |>
  distinct(smsa_name_corrected, adoption_year) |>
  count(is.finite(adoption_year))

  is.finite(adoption_year) n
1 FALSE                    167
2  TRUE                    126